
package Interfaz;

import java.awt.Container;
import java.awt.event.ActionListener;
import static java.awt.image.ImageObserver.WIDTH;

/**
 *
 * @author admin
 */
public class PantallaInicio extends javax.swing.JFrame {
    
   // private PantallaInicio pantallainicio;
    public PantallaInicio() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
                       
    private void initComponents() {

        
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton2.setText("JUGAR");
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 210, 100, -1));

        jButton3.setText("AYUDA");
      
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 260, 100, -1));

        jButton4.setText("SALIR");
        getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 310, 100, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Interfaz/imagen un.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));
        jButton2.setActionCommand("jugar");
        jButton3.setActionCommand("ayuda");
        jButton4.setActionCommand("salir");
        pack();
        
        
    }// </editor-fold>   
    public void riskActionListeners(ActionListener evt){
        jButton2.addActionListener(evt);
        jButton3.addActionListener(evt);
        jButton4.addActionListener(evt);
    }
                            

    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify                     
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
                   
}
